### ISSUE TITLE
pre-commit错误

### ISSUE THREAD

**Issue by co63oc** [PaddlePaddle/PaddleTest#2596]
新建a.txt，内容123，pre-commit安装运行错误

```
(py310) root@iZt4n49r14byh758lhmkk2Z:/nfs/github/paddle/PaddleTest# git commit -m 'Fix'
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://gitee.com/mirrors/black.
[INFO] Initializing environment for https://gitee.com/mirrors_PyCQA/flake8.git.
[INFO] Initializing environment for https://gitee.com/mirrors_PyCQA/flake8.git:pep8-naming.
[INFO] Initializing environment for https://github.com/PyCQA/pylint.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://gitee.com/mirrors/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...


[INFO] Installing environment for https://gitee.com/mirrors_PyCQA/flake8.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...


[INFO] Installing environment for https://github.com/PyCQA/pylint.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/nfs/home/.cache/pre-commit/repoy41wkzu7/py_env-python3.10/bin/python', '-mpip', 'install', '.')
return code: 1
stdout:
    Looking in indexes: http://mirrors.cloud.aliyuncs.com/pypi/simple/
    Processing /nfs/home/.cache/pre-commit/repoy41wkzu7
      Preparing metadata (setup.py): started
      Preparing metadata (setup.py): finished with status 'error'
stderr:
      error: subprocess-exited-with-error
      
      × python setup.py egg_info did not run successfully.
      │ exit code: 1
      ╰─> [63 lines of output]
          /nfs/home/.cache/pre-commit/repoy41wkzu7/py_env-python3.10/lib/python3.10/site-packages/setuptools/dist.py:472: SetuptoolsDeprecationWarning: Invalid dash-separated options
          !!
          
                  ********************************************************************************
                  Usage of dash-separated 'index-url' will not be supported in future
                  versions. Please use the underscore name 'index_url' instead.
          
                  By 2024-Sep-26, you need to update your project and remove deprecated calls
                  or your builds will no longer be supported.
          
                  See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
                  ********************************************************************************
          
          !!
            opt = self.warn_dash_deprecation(opt, section)
          /nfs/home/.cache/pre-commit/repoy41wkzu7/py_env-python3.10/lib/python3.10/site-packages/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
          !!
          
                  ********************************************************************************
                  Requirements should be satisfied by a PEP 517 installer.
                  If you are using pip, you can try `pip install --use-pep517`.
                  ********************************************************************************
          
          !!
            dist.fetch_build_eggs(dist.setup_requires)
          WARNING: The repository located at mirrors.cloud.aliyuncs.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host mirrors.cloud.aliyuncs.com'.
          ERROR: Could not find a version that satisfies the requirement setuptools_scm (from versions: none)
          ERROR: No matching distribution found for setuptools_scm
          Traceback (most recent call last):
            File "/nfs/home/.cache/pre-commit/repoy41wkzu7/py_env-python3.10/lib/python3.10/site-packages/setuptools/installer.py", line 101, in _fetch_build_egg_no_warn
              subprocess.check_call(cmd)
            File "/data/anaconda3/envs/py310/lib/python3.10/subprocess.py", line 369, in check_call
              raise CalledProcessError(retcode, cmd)
          subprocess.CalledProcessError: Command '['/nfs/home/.cache/pre-commit/repoy41wkzu7/py_env-python3.10/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpb4eabi61', '--quiet', '--index-url', 'http://mirrors.cloud.aliyuncs.com/pypi/simple/', 'setuptools_scm']' returned non-zero exit status 1.
          
          The above exception was the direct cause of the following exception:
          
          Traceback (most recent call last):
            File "<string>", line 2, in <module>
            File "<pip-setuptools-caller>", line 34, in <module>
            File "/nfs/home/.cache/pre-commit/repoy41wkzu7/setup.py", line 3, in <module>
              setup(use_scm_version=True)
            File "/nfs/home/.cache/pre-commit/repoy41wkzu7/py_env-python3.10/lib/python3.10/site-packages/setuptools/__init__.py", line 102, in setup
              _install_setup_requires(attrs)
            File "/nfs/home/.cache/pre-commit/repoy41wkzu7/py_env-python3.10/lib/python3.10/site-packages/setuptools/__init__.py", line 75, in _install_setup_requires
              _fetch_build_eggs(dist)
            File "/nfs/home/.cache/pre-commit/repoy41wkzu7/py_env-python3.10/lib/python3.10/site-packages/setuptools/__init__.py", line 80, in _fetch_build_eggs
              dist.fetch_build_eggs(dist.setup_requires)
            File "/nfs/home/.cache/pre-commit/repoy41wkzu7/py_env-python3.10/lib/python3.10/site-packages/setuptools/dist.py", line 636, in fetch_build_eggs
              return _fetch_build_eggs(self, requires)
            File "/nfs/home/.cache/pre-commit/repoy41wkzu7/py_env-python3.10/lib/python3.10/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
              resolved_dists = pkg_resources.working_set.resolve(
            File "/nfs/home/.cache/pre-commit/repoy41wkzu7/py_env-python3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 829, in resolve
              dist = self._resolve_dist(
            File "/nfs/home/.cache/pre-commit/repoy41wkzu7/py_env-python3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 865, in _resolve_dist
              dist = best[req.key] = env.best_match(
            File "/nfs/home/.cache/pre-commit/repoy41wkzu7/py_env-python3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1135, in best_match
              return self.obtain(req, installer)
            File "/nfs/home/.cache/pre-commit/repoy41wkzu7/py_env-python3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1147, in obtain
              return installer(requirement)
            File "/nfs/home/.cache/pre-commit/repoy41wkzu7/py_env-python3.10/lib/python3.10/site-packages/setuptools/installer.py", line 103, in _fetch_build_egg_no_warn
              raise DistutilsError(str(e)) from e
          distutils.errors.DistutilsError: Command '['/nfs/home/.cache/pre-commit/repoy41wkzu7/py_env-python3.10/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpb4eabi61', '--quiet', '--index-url', 'http://mirrors.cloud.aliyuncs.com/pypi/simple/', 'setuptools_scm']' returned non-zero exit status 1.
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    × Encountered error while generating package metadata.
    ╰─> See above for output.
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
Check the log at /nfs/home/.cache/pre-commit/pre-commit.log
```

**Comment by DDDivano** [comment]
疑似python环境的问题

**Comment by co63oc** [comment]
python 3.10

``` pip list
Package                   Version
------------------------- ----------------
addict                    2.4.0
aiohttp                   3.9.1
aiosignal                 1.3.1
aliyun-python-sdk-core    2.14.0
aliyun-python-sdk-kms     2.16.2
async-timeout             4.0.3
attrs                     23.1.0
Automat                   20.2.0
bcrypt                    3.2.0
blinker                   1.4
certifi                   2023.7.22
cfgv                      3.4.0
chardet                   4.0.0
charset-normalizer        3.3.0
click                     8.0.3
cloud-init                19.1.23
colorama                  0.4.4
command-not-found         0.3
configobj                 5.0.8
constantly                15.1.0
crcmod                    1.7
cryptography              3.4.8
dashscope                 1.14.0
dashvector                1.0.9
datasets                  2.16.1
dbus-python               1.2.18
decorator                 4.4.2
decord                    0.6.0
dill                      0.3.7
distlib                   0.3.8
distro                    1.7.0
distro-info               1.1+ubuntu0.1
einops                    0.7.0
filelock                  3.13.1
frozenlist                1.4.1
fsspec                    2023.10.0
gast                      0.5.4
grpcio                    1.60.0
httplib2                  0.20.2
huggingface-hub           0.20.2
hyperlink                 21.0.0
identify                  2.5.33
idna                      3.3
importlib-metadata        7.0.1
incremental               21.3.0
jeepney                   0.7.1
Jinja2                    3.1.2
jmespath                  0.10.0
jsonpatch                 1.33
jsonpointer               2.4
jsonschema                4.19.1
jsonschema-specifications 2023.7.1
keyring                   23.5.0
launchpadlib              1.10.16
lazr.restfulclient        0.14.4
lazr.uri                  1.0.6
MarkupSafe                2.1.3
modelscope                1.11.0
more-itertools            8.10.0
multidict                 6.0.4
multiprocess              0.70.15
netifaces                 0.11.0
nodeenv                   1.8.0
numpy                     1.26.3
oauthlib                  3.2.2
oss2                      2.18.4
packaging                 23.2
pandas                    2.1.4
pexpect                   4.8.0
pillow                    10.2.0
pip                       22.0.2
platformdirs              4.1.0
pre-commit                3.6.0
protobuf                  3.20.3
ptyprocess                0.7.0
pyarrow                   14.0.2
pyarrow-hotfix            0.6
pyasn1                    0.4.8
pyasn1-modules            0.2.1
pycryptodome              3.20.0
PyGObject                 3.42.1
PyHamcrest                2.0.2
PyJWT                     2.3.0
pyOpenSSL                 21.0.0
pyparsing                 2.4.7
pyserial                  3.5
python-apt                2.4.0+ubuntu2
python-dateutil           2.8.2
python-debian             0.1.43+ubuntu1.1
python-linux-procfs       0.6.3
python-magic              0.4.24
pytz                      2023.3.post1
pyudev                    0.22.0
PyYAML                    6.0.1
referencing               0.30.2
requests                  2.31.0
rpds-py                   0.10.6
scipy                     1.11.4
SecretStorage             3.3.1
service-identity          18.1.0
setuptools                59.6.0
simplejson                3.19.2
six                       1.16.0
sortedcontainers          2.4.0
sos                       4.5.6
ssh-import-id             5.11
systemd-python            234
tomli                     2.0.1
tqdm                      4.66.1
Twisted                   22.1.0
typing_extensions         4.9.0
tzdata                    2023.4
ubuntu-advantage-tools    8001
ubuntu-drivers-common     0.0.0
ufw                       0.36.1
unattended-upgrades       0.1
urllib3                   2.0.7
virtualenv                20.25.0
wadllib                   1.3.6
wheel                     0.37.1
xkit                      0.0.0
xxhash                    3.4.1
yapf                      0.40.2
yarl                      1.9.4
zipp                      1.0.0
zope.interface            5.4.0
```
